---
# From https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml
- name: Check if FS is expandable
  shell: "raspi-config nonint get_can_expand"
  register: fs_filled
  changed_when: False

- name: Print if FS is expandable or not
  debug:
    msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
  when: fs_filled.stdout == '0'

- name: Expand Filesystem
  shell: "raspi-config nonint do_expand_rootfs"
  when: fs_filled.stdout == '0'
  register: has_expand

- name: Reboot immediately if there was a change.
  reboot:
  when: has_expand is changed and not (is_test | bool)
  # Cannot test reboot as it will kill container

# Previous implementation inspiration history:
# see: https://github.com/mikolak-net/ansible-raspi-config
